### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by hrnmodi** [wrseward/pdf-parser#2]
Error while trying to install using composer see attached snapshot
![untitled](https://cloud.githubusercontent.com/assets/6830265/19997703/6b0e9e88-a28e-11e6-9133-5ddafb969c3d.png)

**Comment by wrseward** [comment]
Could you please try the following and tell me if it works:

``` sh
composer require "wrseward/pdf-parser:0.1.0"
```

**Comment by hrnmodi** [comment]
Done! thanks @wrseward
