### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by roomoraaes** [wrseward/pdf-parser#4]
Hey!
First of all I really appreciate you for this repository, it has helped me a lot.
So have a little bug here, after I convert PDF to TEXT I have a text with symbols, I think that is a encoding problem, I have tried fix it but i didn`t make.

Can you help me?

![image](https://user-images.githubusercontent.com/11338238/76047782-9f1a4280-5f42-11ea-81a3-7e27aaca0597.png)

**Comment by wrseward** [comment]
Hello!

I think you might be able to solve this by using the the pdftotext `enc` option as [outlined in this answer](https://unix.stackexchange.com/a/191461)

You should be able to quickly achieve that by using it in the constructor of the main class like so:

```php
$parser = new \Wrseward\PdfParser\Pdf\PdfToTextParser('pdftotext -enc ASCII7');
```
